### ISSUE TITLE
Change SSL model

### ISSUE THREAD

**Issue by coding-amateur1415** [sarulab-speech/UTMOS22#13]
Hello, I have observed that you are utilizing wav2vec_small.pt as your SSL model. what are the steps to configure a different SSL model like wav2vec(large)?

**Comment by Takaaki-Saeki** [comment]
Hi, sorry for the delay.
To change the SSL model,
1. Please run [download_stacking_checkpoints.sh](https://github.com/sarulab-speech/UTMOS22/blob/master/fairseq_checkpoints/download_stacking_checkpoints.sh) to download different SSL models.
2. Specify the SSL model path in https://github.com/sarulab-speech/UTMOS22/blob/6f57475688912d11104fefcb43dde18728f3cc68/strong/configs/model/default.yaml#L9, which is used [here](https://github.com/sarulab-speech/UTMOS22/blob/6f57475688912d11104fefcb43dde18728f3cc68/strong/model.py#L28). Then run a training job.
