### ISSUE TITLE
Is the UTMOS strong learner model published in this project based on wav2vec 2.0 ?

### ISSUE THREAD

**Issue by jiusansan222** [sarulab-speech/UTMOS22#14]
Is the UTMOS strong learner model published in this project based on wav2vec 2.0 ? Thank you!

**Comment by Takaaki-Saeki** [comment]
Hi, thank you for your question. The pretrained model checkpoint for the strong leaner is using wav2vec2.0 base model.  
But you can change the SSL model as in https://github.com/sarulab-speech/UTMOS22/issues/13.

**Comment by jiusansan222** [comment]
Thank you very much, I have one more question. Is this published model the same as the model mentioned in table 2 of the paper?
![image](https://github.com/sarulab-speech/UTMOS22/assets/58416364/8fa3e912-cd54-40d0-8958-80cac874495f)

**Comment by Takaaki-Saeki** [comment]
If you mention the model published in the [huggingface](https://huggingface.co/spaces/sarulab-speech/UTMOS-demo), it is UTMOS strong without phoneme encoder. It is the same as the model "w/o phoneme encoder" in Table2.

The pretrained models published [here](https://github.com/sarulab-speech/UTMOS22/tree/master/strong#pretrained-model) are the same as "UTMOS strong" in Table2.
