### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [sarulab-speech/UTMOS22#17]
Hi,
Great work on this project!
I see that this repo is licensed under the MIT license but the [demo](https://huggingface.co/spaces/sarulab-speech/UTMOS-demo) is licensed under the AFL license.
Might it be possible to switch the demo to the MIT license?
Thank you!

**Comment by fakerybakery** [comment]
Update: I see the LICENSE file has the MIT license, however the README lists the license as "AFL"

**Comment by Wataru-Nakata** [comment]
I have applied your PR

**Comment by fakerybakery** [comment]
Thank yoU!
