### ISSUE TITLE
Can I only evaluate English?

### ISSUE THREAD

**Issue by h0ngc** [sarulab-speech/UTMOS22#20]
Thank you for sharing these good MOS evaluation codes.

Is English the only language available for MOS evaluation?

**Comment by Wataru-Nakata** [comment]
We also provide model weights used for OOD track of voicemos challenge 2022 which is trained on chinese language.
Nevertheless, it works ok on the out of domain languages such as japanese.

**Comment by Wataru-Nakata** [comment]
For the weight trained on chinese, please check out the README of the strong learner https://github.com/sarulab-speech/UTMOS22/blob/master/strong/README.md

**Comment by h0ngc** [comment]
Thank you for your answer.
I will try to use OOD strong model for Korean speech.
What GPU did you use during training? I would like to train and use it when it doesn't work well for korean speech.

**Comment by Wataru-Nakata** [comment]
We used single A100 GPU

**Comment by Wataru-Nakata** [comment]
Closing this as it seems to be completed
Feel free to reopen if necessary

**Comment by ZhengRachel** [comment]
> For the weight trained on chinese, please check out the README of the strong learner https://github.com/sarulab-speech/UTMOS22/blob/master/strong/README.md

@Wataru-Nakata Hi! Thanks for your great work. The OOD checkpoint on the google drive gives a 404 error. Would you mind updating it?
