### ISSUE TITLE
How can I use pretrained model?

### ISSUE THREAD

**Issue by hoyden** [sarulab-speech/UTMOS22#21]
Thanks for your job! I want to evaluate your pretrained model (OOD) on my datasets. But I can't load them directly. How to use it just like in UTMOS-demo?

**Comment by Takaaki-Saeki** [comment]
First you may need to set up the environment as described [here](https://github.com/sarulab-speech/UTMOS22/tree/master/strong). Then you can download pretrained strong learners trained for OOD [here](https://github.com/sarulab-speech/UTMOS22/tree/master/strong). You can use these models for prediction with the command described [here](https://github.com/sarulab-speech/UTMOS22/tree/master/strong). If you want to run prediction with stacking, see [here](https://github.com/sarulab-speech/UTMOS22/tree/master/stacking/ensemble_multidomain_scripts).

**Comment by nshmyrev** [comment]
There is a simple wrapper https://github.com/fakerybakery/utmos
