### ISSUE TITLE
Varying predictions on same files (UTMOS-demo)

### ISSUE THREAD

**Issue by lbehringer** [sarulab-speech/UTMOS22#22]
Hi,

I was trying out the quick predictions using the UTMOS-demo and `--mode predict_dir` and noticed that when predicting the same directory multiple times with `batch_size` > 1, the predicted scores will vary each time. With `batch_size` 1, the values are consistent, but the order in the created csv file will be different each time, making it impossible to attribute a score to a specific file.

For `--mode predict_file`, the score is consistent.

**Comment by Wataru-Nakata** [comment]
This is due to the zero padding inserted to the input wav when making a batch. If you want a precise prediction, You should only use batch_size of 1. 
Feel free to reopen the issue when needed.
