### ISSUE TITLE
Pretrained strong model

### ISSUE THREAD

**Issue by sinhprous1** [sarulab-speech/UTMOS22#8]
Hello team. Thank for your amazing work! Could you please publish the pretrained checkpoint of the strong model? Thanks in advance!

**Comment by Takaaki-Saeki** [comment]
We've published pretrained models of UTMOS strong.
Please see the [readme](https://github.com/sarulab-speech/UTMOS22/blob/master/strong/README.md).

**Comment by sinhprous1** [comment]
Thank you so much!
